### ISSUE TITLE
Should not change the working directory

### ISSUE THREAD

**Issue by jimdickinson** [theskumar/python-dotenv#146]
I'm using python-dotenv with Flask and noticed that with a .env file in the parent directory of my app and without one in the app directory, the Flask debugging mode changes the working directory to my parent directory and the code reloader is broken, leaving me with a broken app. Removing python-dotenv fixes the problem.

**Comment by aebrookes** [comment]
This is a feature of Flask rather than python-dotenv. As described [here in the documentation](http://flask.pocoo.org/docs/dev/cli/#environment-variables-from-dotenv), Flask will change the working directory to the location of your .env file. This means that, for example, your FLASK_APP environment variable needs to be relative to the location of the .env file. 

You can see precisely where Flask does this [in the source code here](https://github.com/pallets/flask/blob/master/flask/cli.py#L617).

**Comment by bbc2** [comment]
Thanks for the explanation @aebrookes.  This indeed doesn't seem to be an issue caused by python-dotenv.

> Removing python-dotenv fixes the problem.

Flask has python-dotenv as an optional dependency, and specific code that runs only if python-dotenv is present.  That's why removing it would work around your problem.
