### ISSUE TITLE
Support command expansion

### ISSUE THREAD

**Issue by josephong** [theskumar/python-dotenv#155]
dotenv's such as for [ruby](https://github.com/bkeepers/dotenv) support command expansion. I was wondering if the same could be added for python-dotenv?

This would likely solve a few problems, especially ones related to project roots in both this repo and dependent repositories:
https://github.com/theskumar/python-dotenv/issues/133
https://github.com/pypa/pipenv/issues/2804

**Comment by thehesiod** [comment]
yes!  Would like to be add things like: `FOO=$(echo foo)`  or ```FOO=`echo foo` ```

**Comment by theskumar** [comment]
This goes against the best practises of using .env for storing application config. 

This will lead to security concerns due to random code execution during runtime I would suggest going with a custom python file for storing your config and avoid using .env file or maybe postprocess the string value you get from the .env file.
