### ISSUE TITLE
unload env feature request

### ISSUE THREAD

**Issue by jkornblum** [theskumar/python-dotenv#166]
Is there any functionality currently to unload environment?
I'm performing some integration testing with pytest, I'd like to unload my environment after completing test.

On *nix based systems I think its `unset <myvar>`.

**Comment by HitLuca** [comment]
Not a project maintainer, but for the moment you could create a dummy .env file that has all the required variables but empty values, and load it with `override=True` option

**Comment by HitLuca** [comment]
You made me learn about the `unset` command, nice. +1 for this feature

**Comment by bbc2** [comment]
If you run your tests with Python, what about using something like the following:

```python
with mock.patch.dict(os.environ, {}):
    # do test that modifies environment
```

This cleans up the environment after the `with` block, so that other tests or instructions don't see the environment changes that the test made.  You can add `clean=True` to `dict(...)` to run the test in a clean environment, instead of inheriting variables from the initial environment.

Would that work for you?  Or is there something I'm missing about your use case?
