### ISSUE TITLE
dotenv run echo $my_key returns nothing

### ISSUE THREAD

**Issue by kulmam92** [theskumar/python-dotenv#230]
dotenv run echo doesn't return value
```
> dotenv set MY_PATH test
MY_PATH=test
> dotenv list
MY_PATH=test
>dotenv run echo $MY_PATH

>
```

However, dotenv run env show values from .env
```
> dotenv run env
TERM_SESSION_ID=w0t0p0:0BE9EB7C-0128-4EAA-9027-63D05A16F275
.....
MY_PATH=test
>
```

**Comment by bbc2** [comment]
I'm afraid your command won't work because your shell replaces the variable before passing it to python-dotenv.

```bash
dotenv run echo $MY_PATH
```

is turned into the following before being executed:

```bash
dotenv run echo 
```

You could fix this by quoting the variable (`'$MY_PATH'`) but that won't work either because python-dotenv runs the command directly, not via a shell.

```bash
> dotenv run echo '$MY_PATH'
$MY_PATH
```

What you need to do is ask for a shell to be executed:

```bash
> dotenv run -- bash -c 'echo $MY_PATH'
test
```

I hope this helps.
