### ISSUE TITLE
Reload env?

### ISSUE THREAD

**Issue by ggregoire** [theskumar/python-dotenv#252]
Would be useful for python daemons and updating environment variables dynamically.

So far I'm trying this but it doesn't work:

.env

```python
LOGGING_LEVEL= # I want to be able to change this at any time
```

constants.py

```python
dotenv.load_dotenv() # first load at the start of the daemon

# …setting bunch of constants with os.getenv…

def get_logging_level():
    dotenv.load_dotenv(override=True) # trying to reload each time I call this function
    return os.getenv("LOGGING_LEVEL") or logging.WARNING
```

main.py

```python
from .constants import get_logging_level

def main():
    while True:
        logging.basicConfig(level=get_logging_level())
        
        # …doing some stuff…

        sleep(30)

if __name__ == "__main__":
    main()
```

**Comment by bbc2** [comment]
I think python-dotenv is working fine in your case.

Try replacing `logging.basicConfig(level=get_logging_level())` with the following lines and you'll see that the environment variable is updated:

```python
level = get_logging_level()
print(level)
logging.basicConfig(level=level)
```

So I think you have an issue with the `logging` module rather than python-dotenv.  Does that make sense?

**Comment by bbc2** [comment]
I'm assuming this is solved.  Let us know if that's not the case.
