### ISSUE TITLE
Broken SayThanks badge still present on pypi page

### ISSUE THREAD

**Issue by Foorack** [theskumar/python-dotenv#304]
Related: https://github.com/theskumar/python-dotenv/pull/294

> I removed the "saythanks" link since it is dead.

The badge is still present on the https://pypi.org/project/python-dotenv/ page.

**Comment by jobveldhuis** [comment]
This text you are referencing is the `long_description` in `setup.py`. It has not been updated on pypi because there has not been a new version release since this patch was introduced. When a new version is released, this will be updated automatically -- taking in the latest information from README and CHANGELOG.

**Comment by bbc2** [comment]
Fixed with the new release.
