### ISSUE TITLE
Type conversion when output via dotenv_values()

### ISSUE THREAD

**Issue by DigitalWolf98** [theskumar/python-dotenv#309]
**Hello everyone 👋**

I suggest making an automatic conversion of the value to the desired type,
when output via the function: dotenv_values()

as suggested in their answer -
[kederrac & Kevin Languasco](https://stackoverflow.com/questions/61165574/cast-and-type-env-variables-using-file)
P.S. There may be other ways, but this is the first one I found.

When looping through the `dotenv_values()` dictionary and getting the value type, it always returns a string type.

**main.py file**:
``` Python
# Importing packages & modules
from os import getenv
from dotenv import load_dotenv, dotenv_values

# Setup environmnet variables
load_dotenv()

for k, v in dotenv_values().items():
    print("Key: {} | Val: {} | Type: {}".format(
        key, val,
        type(val)
    )
```
**Output into console:**
``` Bash
Key: string_key | Val: hello | Type: <class 'str'>
Key: digit_key | Val: 2021 | Type: <class 'str'>
Key: bool_key | Val: True | Type: <class 'str'>
```

As we can see the types don't match the values.

Yes, can "force" each developer to write their own implementation of the type conversion, rejecting my idea, but the question is - why ?!
Your library already has a place where you can write in the `dotenv_values()` method, thus it will save many developers from writing an extension to your library.

**Comment by bbc2** [comment]
The purpose of python-dotenv is to help you get environment variables from a file.  Environment variables are strings and this package will give you those strings (either via `os.environ` with `load_dotenv` or directly with `dotenv_values`.  For now, adding code to automatically parse those strings into other types of values is not something we plan to add to this library.  See https://github.com/theskumar/python-dotenv/issues/291#issuecomment-782870888 for a more in-depth answer.

That being said, I thank you for your feedback.  It helps me understand what users want to do with the library.

By the way, this isn't related to your problem but I'd like to point out that the `load_dotenv()` in your code is not necessary since you use `dotenv_values` after that.

**Comment by DigitalWolf98** [comment]
Good afternoon!

p. s. Immediately apologize if I write again in the wrong issues.

As I understand from what I read in request [#291](https://github.com/theskumar/python-dotenv/issues/291#issuecomment-782870888), you yourself do not want to improve your brainchild, well, this is your right and no one has the right to tell you what to do.
I, given your desire to continue to bring something new, will most likely have to unfortunately abandon your library and find what I really lack, or spend a week at most to implement it, although it would take you much less time, and you already have a team that can help with this.
