### ISSUE TITLE
auto_load_dotenv

### ISSUE THREAD

**Issue by xyxz-web** [theskumar/python-dotenv#316]
There are some tools e.g. Prefect that evaluate environment variables at the same time as importing them.
Therefore you would have to write load_dotenv() before importing them, which is a code style I don't really like.
As a simple solution I'd suggest adding a module auto_load_dotenv to python-dotenv that does nothing apart from having the side effect of calling load_dotenv().
What is your opion about this idea?

**Comment by bbc2** [comment]
It's an interesting use case but I don't think it's worth a new module in python-dotenv.  If you need some variables to be loaded from a file before a module is imported, I would recommend doing so explicitly.   That it is bad style is perhaps due to the fact that it's rather uncommon to configure software that way, so I wouldn't want to encourage it with a new feature in our library.  In general, the order in which modules are imported shouldn't be important.
