### ISSUE TITLE
set_key returns previous value

### ISSUE THREAD

**Issue by nandinimaheshwari7107** [theskumar/python-dotenv#366]
Hi,
I've noticed that when we load the .env file using load_dotenv() and then call set_key() for one of the fields, even though set_key() returns the new value and the .env file is updated with the new value - for the rest of the execution of the script, the value referenced for that field (os.getenv()) is still the old one. It only references the updated value from the next execution onwards. 
I believe that could be a result of the context manager being used to store the .env content (not sure yet, still going through the source code) but wouldn't it be better if the updated value is returned the very next time that the field is referenced in the code without having to execute the script again?

**Comment by bbc2** [comment]
I think your description is correct. Another way to illustrate this:

```python
dotenv.load_dotenv()  # If the .env contains `foo=a`, `os.environ` now has `{"foo": "a", ...}`.
dotenv.set_key(".env", "foo", "b")  # The .env now contains `foo='b'` but `os.environ` is unchanged.
dotenv.load_dotenv()  # This doesn't do anything because `foo` is already defined in `os.environ`.
dotenv.load_dotenv(override=True)  # This changes `os.environ` to contain `{"foo": "b"}`.
```

I see two main implementation choices here:

1. `set_key` changes the `.env` file but not `os.environ`.
2. `load_dotenv` doesn't override variables already defined in `os.environ` unless the `override` keyword argument is set to `True` (it is `False` by default).

While both are probably debatable, the current behavior is not absurd in my opinion. (1) seems OK because the goal is to change the `.env` file, not the environment, and (2) is explained by our goal: prioritizing the actual environment (`os.environ`) over `.env` files to favor the building of 12-factor applications.

Does that make sense?  I think, in your case, using `override=True` could work.

**Comment by theskumar** [comment]
@nandinimaheshwari7107 Please open the issue again if @bbc2 response doesn't solve your use-case. Thanks for your contribution.
