### ISSUE TITLE
how to set owner and permissions when writing variables to .env

### ISSUE THREAD

**Issue by KeygenLLC** [theskumar/python-dotenv#367]
I'm writing 1 variable into an `.env` file when my script loads (port number). This works fine and also loads up the existing variables.

However, it seems to be changing the owner to `root` and `chmod 600` when it writes to the `.env`. This prevents other scripts from loading the `.env` since I'm not logged in as root and am running my scripts locally, logged in under username. Right now I'm just `chmod 644` on the `.env` file after writing the variable to it, but was hoping there was a cleaner way to do this.

Apologies if this is some basic thing and unrelated to the package. New to python.

Here is the code:
```python
import dotenv
from dotenv import load_dotenv

load_dotenv()
#-------------------------------------------
# load in variables here and assign to dicts
#-------------------------------------------
# generate port number
port_number = random.randint(49152, 65535)
dotenv_file = '.env'
os.environ['PORT'] = str(port_number)
dotenv.set_key(dotenv_file, 'PORT', os.environ['PORT'])
os.chmod(dotenv_file, 0o644) # second script gets permission denied without this
# load in some other vars here #
# load in the new variable
PORT = int(os.getenv('PORT'))
```
second script
```python
PORT = int(os.getenv('PORT'))
# this errors, of course because of file permissions
#   PORT = int(os.getenv('PORT'))
# PermissionError: [Errno 13] Permission denied:
```

**Comment by nandinimaheshwari7107** [comment]
Hi @KeygenLLC 
This behavior occurs because the set_key() uses the python core module's function [tempfile.NamedTemporaryFile](https://github.com/theskumar/python-dotenv/blob/2471a5af1027acca27f8d326ddb97b1d43a2ba23/src/dotenv/main.py#L138) to update .env value. As per [StackOverflow](https://stackoverflow.com/a/10541972), tempfile.NamedTemporaryFile **always** creates files with permission 0600 and does not accept a constructor argument to set any alternate value.
So, I think what you're doing currently is correct. Maybe you could try encompassing the set_key() and chmod logic within a function that you could call everywhere - just a suggestion.
Hope this helps! 👍🏻
