### ISSUE TITLE
Need clarity (perhaps in documentation) regarding when a value returned from `DotEnv.dict()` can be `None`

### ISSUE THREAD

**Issue by posita** [theskumar/python-dotenv#371]
The return type of [`DotEnv.dict()` is `Dict[str, Optional[str]]`](https://github.com/theskumar/python-dotenv/blob/ba9408c5048e8e512318df423541d2b44ac6019f/src/dotenv/main.py#L66), but it's not clear under what circumstances a value would be `None`. I haven't delved into the parsing code, but it's not clear to me, even after looking at (e.g.) `resolve_variables`, `parse`, etc.

Under what circumstances would one expect to receive a value of `None` for a particular key? Can this be documented?

**Comment by bbc2** [comment]
This possibility was added in https://github.com/theskumar/python-dotenv/pull/220.  It makes it possible to have a variable name with no value in the .env file (i.e. just `<name>` instead of `<name>=<value>`), which is reflected as the name being associated with `None` in the resulting dict.

I agree this should be documented, at least for `dotenv_values` (`DotEnv.dict` is a bit less important because it's an internal API).
