### ISSUE TITLE
encoding not an option using set_key

### ISSUE THREAD

**Issue by gbrabelo** [theskumar/python-dotenv#378]
You can create and read a .env using the main.DotEnv class with an encoding, but the functions of setting key/unsetting do not act accordingly with the encoding set nor have an option to set it. - They both use the rewrite contextmanager

**Comment by bbc2** [comment]
`DotEnv` and `rewrite` are internal objects so I'm going to ignore them for now.

If I understand correctly, what you are looking for is an `encoding` parameter for `dotenv.set_key` and `dotenv.unset_key`, similar to the one `dotenv.load_dotenv` and `dotenv.dotenv_values` already have.  Is that correct?

If that's what you meant, I can probably consider adding this since it would make sense and should be easy to do.

**Comment by gbrabelo** [comment]
That's exactly right! It makes sense cause otherwise you can't edit an env file that was loaded with a different encoding!

**Comment by bbc2** [comment]
I just opened a pull request (#379). I hope that it will solve your problem.

**Comment by gbrabelo** [comment]
Great! Thanks!
